### ISSUE TITLE
Melhorias necessárias no código

### ISSUE THREAD

**Issue by tashima42** [Diego-Lopes-Ferreira/Email-sign-generator#7]
### TODO

- [x] Descomentar no código a mensagem de que a assinatura foi copiada `linha 110/index.js`
- [x] Remover arquivo `intermediario.html`
- [x] Atualizar o README 
- [x] Criar novo tutorial e colocar no repositório (criar um gh pages para ele?)
- [x] Adicionar comentários ao JavaScript 
- [x] Adicionar comentários ao HTML
- [x] melhorar o CSS responsivo
- [x] organizar os diretórios do repo
- [ ] organizar as branchs
